# Generated by Django 4.0.6 on 2022-10-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_advertisement_providerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='ProviderID',
            new_name='UserID',
        ),
    ]
